apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: my-app
  name: my-app
spec:
  containers:
  - env:
    - name: GET_HOSTS_FROM
      value: dns
    image: gcr.io/alioua-service/my-app:latest
    name: my-app
    ports:
    - containerPort: 3000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
